package org.sendoh.service

import org.sendoh.model.Customer
import org.sendoh.request.NewCustomerRequest
import java.math.BigDecimal

/**
 * Provide features for customer. A customer must first register so can be served.
 * Without registration no feature should be provided.
 *
 * A customer is identified by uuid that is generated by email, and use this id can operate the features provided
 * by the service
 *
 * */

interface CustomerService {
    /**
     * Register a new customer and return a customer with a unique id generated by email
     * one email only allows one registration
     */
    fun register(newCustomerRequest: NewCustomerRequest): Customer

    /**
     * Find a customer by id
     */
    fun get(id: String): Customer?

    /**
     * Find all customers
     */
    fun getAll(): List<Customer>

    /**
     * Check if a customer can rent car with id
     */
    fun canRent(id: String): Boolean

    /**
     * Registered customer pays the rent with id
     */
    fun payRent(id: String, rent: BigDecimal)
}
